---
- name: Installing PostgreSQL on AlmaLinux
  hosts: almalinux
  become: true

  vars:
    pg_version: "13.20"
    pg_data: "/var/lib/pgsql/{{ pg_version }}/data"
    pg_socket_dir: /var/run/postgresql
    pg_port: 5432
    db_user: "student"
    db_password: "studentpass"
    allowed_ip: ""

  tasks:
    - name: Install PostgreSQL
      ansible.builtin.dnf:
        name:
          - postgresql-server-{{ pg_version }}
          - python3-psycopg2
        state: present
        use_backend: dnf4

    - name: Check if PostgreSQL sockets directory exists
      ansible.builtin.stat:
        path: "{{ pg_socket_dir }}"
      register: pg_socket_dir_stat
    
    - name: Create a folder for PostgreSQL sockets
      ansible.builtin.file:
        path: "{{ pg_socket_dir }}"
        state: directory
        owner: postgres
        group: postgres
        mode: '0750'
      when: not (pg_socket_dir_stat.stat.exists and pg_socket_dir_stat.stat.isdir)

    - name: Check if PostgreSQL data directory exists
      ansible.builtin.stat:
        path: "{{ pg_data }}"
      register: pg_data_stat

    - name: Check for existing PostgreSQL data files
      ansible.builtin.find:
        paths: "{{ pg_data }}"
        file_type: file
      register: pg_data_files
      when: pg_data_stat.stat.exists and pg_data_stat.stat.isdir
    
    - name: Create a folder for PostgreSQL data
      ansible.builtin.file:
        path: "{{ pg_data }}"
        state: directory
        owner: postgres
        group: postgres
        mode: '0750'
      when: pg_data_files is defined and (pg_data_files.files | default([]) | length == 0)

    - name: Initialize the DB cluster
      ansible.builtin.command: "initdb -D {{ pg_data }}"
      become: true
      become_user: postgres
      when: pg_data_files is defined and (pg_data_files.files | default([]) | length == 0)

    - name: Change unix_socket_directories in the config
      ansible.builtin.lineinfile:
        path: "{{ pg_data }}/postgresql.conf"
        regexp: '^#?unix_socket_directories =.*'
        line: "unix_socket_directories = '{{ pg_socket_dir }}'"
        state: present
        owner: postgres
        group: postgres

    - name: Setting up listen_addresses
      ansible.builtin.lineinfile:
        path: "{{ pg_data }}/postgresql.conf"
        regexp: "^#?(listen_addresses\\s*=\\s*).*$"
        line: "listen_addresses = '*'"
        owner: postgres
        group: postgres
        mode: '0644'

    - name: Adding access rule for the second server user
      ansible.builtin.lineinfile:
        path: "{{ pg_data }}/pg_hba.conf"
        regexp: '^host\s+all\s+{{ db_user }}\s+{{ allowed_ip }}/32\s+md5\s*$'
        line: "host all {{ db_user }} {{ allowed_ip }}/32 md5"
        owner: postgres
        group: postgres
        mode: '0640'
        state: present

    - name: Starting PostgreSQL
      ansible.builtin.shell: |
        if ! pg_ctl status -D {{ pg_data }} >/dev/null 2>&1; then
          pg_ctl start -D {{ pg_data }} 2>/dev/null
          exit_code=$?
          if [ $exit_code -eq 1 ]; then
            pg_ctl stop -D {{ pg_data }} -m fast >/dev/null 2>&1
            pg_ctl start -D {{ pg_data }} 2>/dev/null
          else
            exit $exit_code
          fi
        fi
      become: true
      become_user: postgres
      args:
        chdir: /var/lib/pgsql
      register: pg_start
      failed_when: pg_start.rc != 0 and pg_start.rc != 1
      changed_when: '"started" in pg_start.stdout'

    - name: Checking database availability
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: "{{ pg_port }}"
        timeout: 30

    - name: Create DB user
      community.postgresql.postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        role_attr_flags: "CREATEDB,CREATEROLE,LOGIN"
        login_user: postgres
        login_host: localhost
      become_user: postgres
    
    - name: The first server is ready to accept external connections
      ansible.builtin.command: >
        echo ""
      changed_when: false