FROM almalinux:9.5

RUN dnf install -y openssh-server sudo && \
    dnf clean all

RUN ssh-keygen -A && \
    echo 'root:root_password' | chpasswd && \
    sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
    mkdir -p /root/.ssh && \
    chmod 700 /root/.ssh

CMD [ "/usr/sbin/sshd", "-D" ]